name: CI


on:
  push:
    branches: [ main, dev_demo, Charly, Anasthasia ]
  pull_request:
    branches: [ main, dev_demo, Charly, Anasthasia ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Install ruff (pip)
        run: pip install ruff

      - name: Lint with ruff
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          which ruff
          ruff --version
          ruff check app_streamlit

      - name: Build Docker image (versionnée)
        run: docker build -t efficient_frontier:latest .

      - name: Import check in Docker image
        run: docker run --rm efficient_frontier:latest uv run python -c "import app_streamlit.app; import app_streamlit.app_oop"

